version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: wellster
      POSTGRES_PASSWORD: wellster
      POSTGRES_DB: wellster_api_development
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: wellster
      DB_PASSWORD: wellster
    depends_on:
      - db

volumes:
  postgres_data: